### ISSUE TITLE
Build system: "Error: no such file or directory"

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#220]
Hi @kriskowal, 

I have trouble with `npm run generate` in our new build system with the files of #219 (https://github.com/hfg-gmuend/openmoji/pull/219/commits/3528cf5fa1345acd00621ecb8e7ac36bbf825c62). Could you have a look?

Also I'm wondering how to clean the cache on a local file? Is is just removing `.git/refs/memos/*`?

```
$ npm run generate

> openmoji@12.2.0 generate /Users/bene/Documents/GitHub/openmoji
> ./helpers/generate.sh

-------------------------------------------
👉 helpers/generate-data-tables.js
-------------------------------------------
👉 helpers/generate-index-html.js
-------------------------------------------
👉 helpers/pretty-src-svg.sh
21 changes
Caching refs/memos/pretty-src-svg
-------------------------------------------
👉 helpers/export-svg.sh
Exporting skintone SVGs
10 changes
Caching refs/memos/export-svg-skintones
Exporting non-skintone color SVGs
21 changes
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7E6.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7E5.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F4CC-200D-2699-FE0F.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7E6.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7E7.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7E9.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7E5.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7EB.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7E7.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7EA.svg'.
Error: Error: no such file or directory 'color/svg/1F3F3-FE0F-200D-1F7E8.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7E9-200D-2605-FE0F.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7EB.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7E8.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7EA.svg'.
Error: Error: no such file or directory 'color/svg/2691-FE0F-200D-1F7E9.svg'.
Caching refs/memos/export-svg-color
fatal: pathspec 'color/svg/1F3F3-FE0F-200D-1F4CC-200D-2699-FE0F.svg' did not match any files
Extracting black outline SVGs from all color SVGs
No changes
Removing extraneous files: black/618x618/1F1EA-1F1F4.png black/72x72/1F1EA-1F1F4.png black/svg/1F1EA-1F1F4.svg color/618x618/1F1EA-1F1F4.png color/72x72/1F1EA-1F1F4.png color/svg/1F1EA-1F1F4.svg
-------------------------------------------
👉 helpers/export-png.sh
Scale 72x72
16 changes
Caching refs/memos/export-png-72
fatal: pathspec 'black/72x72/1F3F3-FE0F-200D-1F4CC-200D-2699-FE0F.png' did not match any files
fatal: pathspec 'black/svg/2691-FE0F-200D-1F7E5.svg' did not match any files
fatal: pathspec 'color/72x72/2691-FE0F-200D-1F7E5.png' did not match any files
Scale 618x618
16 changes
Caching refs/memos/export-png-618
fatal: pathspec 'black/618x618/1F3F3-FE0F-200D-1F4CC-200D-2699-FE0F.png' did not match any files
fatal: pathspec 'black/svg/2691-FE0F-200D-1F7E5.svg' did not match any files
fatal: pathspec 'color/618x618/2691-FE0F-200D-1F7E5.png' did not match any files
-------------------------------------------
👉 helpers/clean.sh

```

**Comment by kriskowal** [comment]
I’ve checked out the proposed change and reproduced this outcome precisely. My initial impression is that this is not likely a caching problem, but because the new build system uses the content of openmoji.json to determine expected source file locations, there might be a data inconsistency. It might also be possible to improve the build scripts to discover this kind of inconsistency early and raise a more informative error.

If this is a caching issue, the recourse to clear the cache is:

```
for ref in export-png-618  export-png-72  export-svg-color export-svg-skintones pretty-src-svg; do git update-ref -d refs/memos/$ref; done
```

It would make sense to add this a s a script to package.json for convenience:

```json
{
  "scripts": {
    "cache-clear": "for ref in export-png-618  export-png-72  export-svg-color export-svg-skintones pretty-src-svg; do git update-ref -d refs/memos/$ref; done",
    "cc": "npm run cache-clear"
  }
}
```

I’m running a rebuild having cleared my cache now. Will post an update shortly.

**Comment by kriskowal** [comment]
Same results with a clear cache. I’m looking into whether there’s a data consistency issue (doesn’t look like it so far) or something else. Looks like it goes off the rails toward the beginning of the pipeline.

**Comment by kriskowal** [comment]
I’ve isolated a few small bugs in the build system. I’ll propose a diff in half a day.

**Comment by b-g** [comment]
Hi @kriskowal, Super! Many thanks for the fix! But if I run it on the files of #221 (ac82758428a98d79d9ea3b1a3dc3b92b1641f38c):

1. `npm run cc`
2. `npm run generate`
3. I get the following errors ...

Can you reproduce?

Also: running `npm run test-dev` and `npm test` show that `🇩🇯 1F1E9-1F1EF.svg` is broken. But this seems not to be the cause of the bug, or? The tests should also ensure that we don't have data problems in terms of src folder and data/openmoji.json

```
$ npm run generate

> openmoji@12.2.0 generate /Users/bene/Documents/GitHub/openmoji
> ./helpers/generate.sh

-------------------------------------------
👉 helpers/generate-data-tables.js
-------------------------------------------
👉 helpers/generate-index-html.js
-------------------------------------------
👉 helpers/pretty-src-svg.sh
2069 changes
Caching refs/memos/pretty-src-svg
-------------------------------------------
👉 helpers/export-svg.sh
Exporting skintone SVGs
1440 changes
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104
      path.join(folderSrc, skintoneBaseEmoji.group, skintoneBaseEmoji.subgroups, skintoneBaseEmoji.hexcode + '.svg'),
                                             ^

TypeError: Cannot read property 'group' of undefined
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-skintones.js:104:46)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Caching refs/memos/export-svg-skintones
Exporting non-skintone color SVGs
2069 changes
/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-color.js:20
  writeSvg(destFilePath, doc.querySelector('svg').outerHTML);
                                                 ^

TypeError: Cannot read property 'outerHTML' of null
    at generateSvg (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-color.js:20:50)
    at Object.<anonymous> (/Users/bene/Documents/GitHub/openmoji/helpers/lib/export-svg-color.js:34:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Caching refs/memos/export-svg-color
Extracting black outline SVGs from all color SVGs
197 changes
Caching refs/memos/export-svg-black
-------------------------------------------
👉 helpers/export-png.sh
Scale 72x72
7018 changes
Caching refs/memos/export-png-72
Scale 618x618
7018 changes
Caching refs/memos/export-png-618
-------------------------------------------
👉 helpers/clean.sh
```

**Comment by b-g** [comment]
Hi @kriskowal, I've spent some time digging into it ... I think I found the bug https://github.com/hfg-gmuend/openmoji/commit/b5dbc497ca17b9a4960bab95e714d48b18731476. I believe a single variable name was mixed up :) Will investigate further.

**Comment by b-g** [comment]
I think this was it. Yay! Seems to be working again! Many 🙏 @kriskowal
